[theme]
name = 'Fuchsia-Regular'
comment = 'First OpenSource port of FuchsiaOS Regular Windows Cursors'
website = 'https://github.com/ful1e5/fuchsia-cursor'

[config]
bitmaps_dir = ''   # This config will assigned with `ctgen -d <path>`
out_dir = '../themes'
platforms = 'windows'


[cursors]
[cursors.fallback_settings]
win_sizes = ["22:32", "32:48", "43:64", "64:96", "86:128"]
x_hotspot = 128
y_hotspot = 128
win_delay = 1


[cursors.all-scroll]
png = 'all-scroll.png'
win_name = 'Move'

[cursors.move]
png = 'move.png'
win_name = 'Grabbing'

[cursors.bottom_left_corner]
png = 'bottom_left_corner.png'
win_name = 'Dng2'

[cursors.bottom_right_corner]
png = 'bottom_right_corner.png'
win_name = 'Dng1'

[cursors.cross]
png = 'cross.png'
win_name = 'Cross'

[cursors.crossed_circle]
png = 'crossed_circle.png'
x_hotspot = 33
y_hotspot = 33
win_name = 'Unavailable'

[cursors.hand1]
png = 'hand1.png'
win_name = 'Pan'

[cursors.hand2]
png = 'hand2.png'
x_hotspot = 33
y_hotspot = 33
win_name = 'Link'

[cursors.left_ptr]
png = 'left_ptr.png'
x_hotspot = 33
y_hotspot = 33
win_name = 'Pointer'

[cursors.left_ptr_watch]
png = 'left_ptr_watch-*.png'
x_hotspot = 32
y_hotspot = 32
win_sizes = "64:96"
win_name = 'Work'

[cursors.pencil]
png = 'pencil.png'
x_hotspot = 55
y_hotspot = 203
win_name = 'Handwriting'

[cursors.question_arrow]
png = 'question_arrow.png'
x_hotspot = 33
y_hotspot = 33
win_name = 'Help'

[cursors.right_ptr]
png = 'right_ptr.png'
x_hotspot = 223
y_hotspot = 33
win_name = 'Alternate'

[cursors.sb_h_double_arrow]
png = 'sb_h_double_arrow.png'
x11_name = 'sb_h_double_arrow'
win_name = 'Horz'

[cursors.sb_v_double_arrow]
png = 'sb_v_double_arrow.png'
win_name = 'Vert'

[cursors.wait]
png = 'wait-*.png'
win_sizes = "64:96"
win_name = 'Busy'

[cursors.xterm]
png = 'xterm.png'
win_name = 'Text'

[cursors.zoom-in]
png = 'zoom-in.png'
x_hotspot = 113
y_hotspot = 113
win_name = 'Zoom-in'

[cursors.zoom-out]
png = 'zoom-out.png'
x_hotspot = 113
y_hotspot = 113
win_name = 'Zoom-out'

[cursors.person]
png = 'person.png'
x_hotspot = 33
y_hotspot = 33
win_name = 'Person'

[cursors.pin]
png = 'pin.png'
x_hotspot = 33
y_hotspot = 33
win_name = 'Pin'
